### PR TITLE
Adding Ryan Sinnet (ryan@rwsinnet.com) as a co-maintainer.

### PR DESCRIPTION
**Pull request by rsinnet**

### CODE REVIEW

**Comment by rsinnet** [comment]
@130s Should I squash into one commit and drop merge commit?

**Review by 130s — APPROVED** [review]
@rsinnet if you can merge, please squash all commits.

**Comment by rsinnet** [comment]
Done rebasing.

**Comment by rsinnet** [comment]
@dirk-thomas @130s This PR should be ready; however, I don't have write access.

**Comment by 130s** [comment]
Turned out I don't either. I assume @dirk-thomas or someone from @ros-visualization/rqt-plugins will take care of this (and other repos) whenever ready.

@rsinnet btw you can squash-merge on Github web interface as you may know, once you gets a write access.

**Comment by dirk-thomas** [comment]
I have added both of you as collaborators (with admin access) to this repo as well as the corresponding [gbp](https://github.com/ros-gbp/rqt_launch-release).

**Comment by dirk-thomas** [comment]
@130s @rsinnet Has either of you had any time to look into any of the open issues since you volunteered as becoming a maintainer?

**Comment by 130s** [comment]
I haven't had any time on this pkg, but is there anything critical going on?

**Comment by dirk-thomas** [comment]
> I haven't had any time on this pkg, but is there anything critical going on?

That depends on what you consider critical. Several of the existing ticket seem to report pretty severe bugs. I will leave it up to you to decide which ones you think should be worked on.

**Comment by 130s** [comment]
I see. Although [active development is not necessarily a maintainer's responsibility](http://wiki.ros.org/MaintenanceGuide#Role_of_a_Maintainer) if I'm not mistaken, I'd be willing to fix issues. I just can't in a foreseeable future. I'm still happy to review when I can.

**Pull request merged**
